on:
  schedule:
    - cron:  '15 14 * * *'
  workflow_dispatch:
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Create Commit
        run: >
          curl https://www.citizenscience.gov/feed.json > feed.json
          if [[ $(git diff --stat) != '' ]]; then
            git add feed.json &&
            git commit -m "Snapshot - ${{ steps.date.outputs.date }}" &&
            git push
          fi
